version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: MotorcycleMicroService.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=motorcycledb;Username=postgres;Password=teste123
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: motorcycledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
